server:
  port: ${PORT:8000}

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/rudikcloud?user=rudik&password=rudik}
  jpa:
    hibernate:
      ddl-auto: validate
  jackson:
    property-naming-strategy: SNAKE_CASE
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

audit:
  ingest-token: ${AUDIT_INGEST_TOKEN:dev-audit-token}
